
###
# @name get_users
GET http://localhost:3000/users/8

###
# @name get_user_friends
GET http://localhost:3000/users/friends/8

###
# @name create_friend_request
POST http://localhost:3000/friend-request
Content-Type: application/json

{
    "senderId": 7,
    "receiverId": 8
}

###
# @name get_pending_friend_requests
GET http://localhost:3000/friend-request/pending/8

###
# @name accept_a_friend_request
PATCH http://localhost:3000/friend-request/accept/8
Content-Type: application/json


###
# @name reject_a_friend_request
PATCH http://localhost:3000/friend-request/reject/7
Content-Type: application/json

###
# @name get_my_friends
GET http://localhost:3000/friendships/me/8