version: '3.8'

services:
  postgres:
    container_name: syncspace-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: syncspace
  mongo:
    container_name: syncspace-mongo
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: docker
  redis:
    container_name: syncspace-redis
    image: redis
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: docker
